[package]
name = "ardemu"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"ardemu_core",
	"ardemu_gui",
	"ardemu_web",
	"ardemu_macros/ardemu_assemble_macro",
	"ardemu_macros/ardemu_asm_parse_macro",
	"ardemu_macros/ardemu_display_instr_macro",
]

[workspace.dependencies]
thiserror = { version = "2.0" }
self-rust-tokenize = "0.4.0"
quote = { version = "1.0.38" }
syn = { version = "2.0.98", features = ["full"] }
proc-macro2 = "1.0"

[dependencies]
ardemu_core = { path = "ardemu_core" }
ardemu_assemble_macro = { path = "ardemu_macros/ardemu_assemble_macro" }