[package]
name = "ardemu_core"
version = "0.1.0"
edition = "2021"

[dependencies]
ardemu_instruction_helper_macro = { path = "../ardemu_macros/ardemu_instruction_helper_macro" }
elf = "0.8.0"
ihex = "3.0.0"
num_enum = "0.7.3"
num-traits = "0.2.19"
self-rust-tokenize = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ardemu_assemble_macro = { path = "../ardemu_macros/ardemu_assemble_macro" }
