[package]
name = "ardemu_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ardemu_core = { path = "../ardemu_core" }
directories = "6.0"
iced = { version = "0.13.1", features = [
  "advanced",
  "highlighter",
  "image",
  "lazy",
  "svg",
  "tokio",
] }
iced_aw = { version = "0.12", default-features = false, features = ["spinner"] }
image = "=0.24.9"
rfd = "0.15.3"
serde = { version = "1.0", features = ["derive"] }
syntect = { version = "5.2.0", features = ["yaml-load"] }
tokio = { version = "1.44.2", features = [
  "fs",
  "io-util",
  "process",
  "rt-multi-thread",
] }
toml = "0.9.5"
triple_buffer = "8.1.0"