[package]
name = "ardemu_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ardemu_core = { path = "../ardemu_core" }
triple_buffer = "8.1.0"
syntect = { version = "5.2.0", features = ["yaml-load"] }
iced = { version = "0.13.1", features = [
	"tokio",
	"lazy",
	"advanced",
	"svg",
	"highlighter",
] }
iced_aw = { version = "0.12", default-features = false, features = ["spinner"] }
tokio = { version = "1.4", features = ["rt-multi-thread", "fs"] }
rfd = "0.15.3"